# Preflight - Infrastructure 
- name: Configure Cluster Nodes
  hosts: "{{ groups['kube-node'] }}"
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
  any_errors_fatal: true
  vars:
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_ssh_private_key_file_name: "id_rsa"
    ansible_user: k8s
    change_dns: true
    dns_server: 10.0.0.254 # SkyTap DNS
    packages:  # Kubespray requirements.txt
      - apparmor
      - aptitude
      - apt-transport-https
      - apt-utils
      - aufs-tools
      - bash-completion
      - ca-certificates
      - conntrack
      - curl
      - gnupg-agent
      - libseccomp2
      - lvm2
      - net-tools
      - python3-apt
      - python3-pip
      - python3-setuptools
      - software-properties-common
      - wget

    ansible_python_interpreter: /usr/bin/python3
 
  tasks:
   # Ping Nodes
   - name: Ping Nodes
     ping:
     tags: 
       - info
   
   # Update Packages
   - name: Update apt repo and cache on Cluster Nodes
     apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
     tags: 
       - updates

   # Upgrade Packages
   - name: Upgrade all packages on Cluster Nodes
     apt: upgrade=dist force_apt_get=yes
     tags: 
       - updates
  
   # Check if reboot is required
   - name: Check if a reboot is needed on all servers
     register: reboot_required_file
     stat: path=/var/run/reboot-required get_md5=no  

   # Install Commmon Packages
   - name: Install Common Packages
     apt:
      name: "{{ packages }}"
      state: latest
      update_cache: yes

   # Add IPs to etc/hosts
   - name: Make sure an entry in /etc/hosts exists
     lineinfile:
      path: /etc/hosts
      regexp: "^{{ ansible_default_ipv4.address }}"
      line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"
      state: present
     tags: network,hostname,dns
      
   # Check for DNS servers
   - name: Get dhcp/dhclient.conf
     shell: cat /etc/dhcp/dhclient.conf | grep domain-name-servers
     ignore_errors: true
     register: dhcp_nameserver_entry

   # This file will rebuild the /etc/resolv.conf file on reboot.   
   # Leverage the private DNS lookup of SkyTap
   - name: Override current DNS entries
     shell: |
        cp /etc/dhcp/dhclient.conf /etc/dhcp/dhclient.conf.{{ 10000 | random }}.bak
        echo "supersede domain-name-servers {{ dns_server }};" >> /etc/dhcp/dhclient.conf
     register: dhcp_update       
     when: change_dns and ("dhcp_nameserver_entry is not defined" or "'{{ dns_server }}' not in dhcp_nameserver_entry.stdout")
   
   # Reboot iniated by Ansible
   - name: Reboot the Debian or Ubuntu server
     reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
     tags: 
       - reboot