---
# Generate ssh key and distribute.
- name: Generate SSH key
  hosts: "{{ groups['installer'][0] }}"
  connection: local
  vars:
    ansible_user: installer
    ssh_key_filename: id_rsa.pub

  vars_prompt:
    - name: "ssh_passphrase"
      prompt: "Enter the passphrase for the SSH key"

  tasks:
    - name: Generate SSH key "{{ ssh_key_filename }}"
      user:
        name: "{{ ansible_user }}"
        generate_ssh_key: yes
        ssh_key_type: rsa
        ssh_key_bits: 4096
        ssh_key_file: .ssh/{{ ssh_key_filename }}
        ssh_key_passphrase: "{{ ssh_passphrase }}"
        force: no

    - name: SSH authorized key
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}" 

# Deploy SSH key to remote hosts.
- name: Deploy SSH keys to remote hosts
  hosts: 
  become: yes
  vars:
    remote_user: k8s

  tasks:
  - name: SSH authorized key.
    authorized_key:
      user: "{{ remote_user }}"
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}" 

# Assign sudo with passwordless.
- name: Assign sudo group with passwordless
  hosts: "all"
  become: yes

  tasks:
    # Ping Nodes
    - name: Ping Nodes
      ping:
      tags: 
       - info

    - name: Setting up Sudo Passwordless
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo  ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'   